Repository wooga/atlas-jenkins-pipeline, pull requests merged in 2021-10, with the labels that each got.

#45 Fix gradleWrapper calling error
  src/net/wooga/jenkins/pipeline/model/Gradle.groovy
  test/groovy/scripts/GradleWrapperSpec.groovy
  vars/gradleWrapper.groovy
Labels: add, atlas-stream, fix, change

#46 explicit property get on publish to avoid jenkins restrictions
  src/net/wooga/jenkins/pipeline/assemble/Assemblers.groovy
  src/net/wooga/jenkins/pipeline/publish/Publishers.groovy
  src/net/wooga/jenkins/pipeline/setup/Setups.groovy
Labels: atlas-stream, fix

#48 Added first platform as main platform
  src/net/wooga/jenkins/pipeline/check/CheckCreator.groovy
  src/net/wooga/jenkins/pipeline/config/Config.groovy
  src/net/wooga/jenkins/pipeline/config/Platform.groovy
  src/net/wooga/jenkins/pipeline/config/WDKConfig.groovy
  test/groovy/net/wooga/jenkins/pipeline/config/ConfigSpec.groovy
  test/groovy/net/wooga/jenkins/pipeline/config/PlatformSpec.groovy
  test/groovy/net/wooga/jenkins/pipeline/config/WDKConfigSpec.groovy
  test/groovy/scripts/JavaCheckSpec.groovy
  test/groovy/scripts/WDKCheckSpec.groovy
  vars/buildGradlePlugin.groovy
Labels: add, atlas-stream
