Repository wooga/atlas-jenkins-pipeline, pull requests merged in 2021-09, with the labels that each got.

#31 Change the WDK NUnit `testResultsPattern` to look only into `unity/test*` directories
  vars/buildWDKAutoSwitch.groovy
Labels: atlas-stream, change

#37 Fix missing guards for coveralls webhook call
  vars/buildJavaLibrary.groovy
  vars/buildJavaLibraryOSSRH.groovy
Labels: atlas-stream, fix

#39 Fix local integration tests
  Jenkinsfile
  buildSrc/build.gradle
  buildSrc/src/test/groovy/integration/VersionPluginIntegrationSpec.groovy
Labels: atlas-stream, fix

#40 Make coveralls webhook call fire and forget
  vars/buildGradlePlugin.groovy
  vars/buildJavaLibrary.groovy
  vars/buildJavaLibraryOSSRH.groovy
  vars/buildPrivateJavaLibrary.groovy
Labels: atlas-stream, fix

#41 Remove sonarqube branch limitation and added branch name property
  test/groovy/specs/BuildGradlePluginSpec.groovy
  vars/buildGradlePlugin.groovy
  vars/buildJavaLibrary.groovy
  vars/buildJavaLibraryOSSRH.groovy
  vars/buildPrivateJavaLibrary.groovy
  vars/buildWDKAutoSwitch.groovy
Labels: add, atlas-stream, remove

#34 Refactor pipeline scripts and added tests
  .gitignore
  Task
  build.gradle
  src/net/wooga/jenkins/pipeline/BuildUtils.groovy
  src/net/wooga/jenkins/pipeline/BuildVersion.groovy
  src/net/wooga/jenkins/pipeline/TestHelper.groovy
  src/net/wooga/jenkins/pipeline/assemble/Assemblers.groovy
  src/net/wooga/jenkins/pipeline/check/CheckCreator.groovy
  src/net/wooga/jenkins/pipeline/check/Checks.groovy
  src/net/wooga/jenkins/pipeline/check/Commands.groovy
  src/net/wooga/jenkins/pipeline/check/Coveralls.groovy
  src/net/wooga/jenkins/pipeline/check/EnclosureCreator.groovy
  src/net/wooga/jenkins/pipeline/check/Enclosures.groovy
  src/net/wooga/jenkins/pipeline/check/Sonarqube.groovy
  src/net/wooga/jenkins/pipeline/config/Config.groovy
  src/net/wooga/jenkins/pipeline/config/DockerArgs.groovy
  src/net/wooga/jenkins/pipeline/config/JenkinsMetadata.groovy
  src/net/wooga/jenkins/pipeline/config/Platform.groovy
  src/net/wooga/jenkins/pipeline/config/SonarQubeArgs.groovy
  src/net/wooga/jenkins/pipeline/config/UnityVersionPlatform.groovy
  src/net/wooga/jenkins/pipeline/config/WDKConfig.groovy
  src/net/wooga/jenkins/pipeline/model/Docker.groovy
  src/net/wooga/jenkins/pipeline/model/Gradle.groovy
  src/net/wooga/jenkins/pipeline/publish/Publishers.groovy
  src/net/wooga/jenkins/pipeline/setup/Setups.groovy
  test/groovy/net/wooga/jenkins/pipeline/config/BuildVersionSpec.groovy
  test/groovy/net/wooga/jenkins/pipeline/config/ConfigSpec.groovy
  test/groovy/net/wooga/jenkins/pipeline/config/DockerArgsSpec.groovy
  test/groovy/net/wooga/jenkins/pipeline/config/PlatformSpec.groovy
  test/groovy/net/wooga/jenkins/pipeline/config/SonarQubeArgsSpec.groovy
  test/groovy/net/wooga/jenkins/pipeline/config/WDKConfigSpec.groovy
  test/groovy/scripts/BuildGradlePluginSpec.groovy
  test/groovy/scripts/BuildJavaLibraryOSSRHSpec.groovy
  test/groovy/scripts/BuildJavaLibrarySpec.groovy
  test/groovy/scripts/BuildPrivateJavaLibrarySpec.groovy
  test/groovy/scripts/BuildWDKAutoSwitchSpec.groovy
  test/groovy/scripts/JavaCheckSpec.groovy
  test/groovy/scripts/WDKCheckSpec.groovy
  test/groovy/specs/BuildGradlePluginSpec.groovy
  test/groovy/tools/DeclarativeJenkinsSpec.groovy
  test/groovy/tools/FakeCredentialStorage.groovy
  test/groovy/tools/FakeEnvironment.groovy
  test/groovy/tools/FakeMethodCalls.groovy
  test/resources/scripts/checkTest.groovy
  vars/buildGradlePlugin.groovy
  vars/buildJavaLibrary.groovy
  vars/buildJavaLibraryOSSRH.groovy
  vars/buildPrivateJavaLibrary.groovy
  vars/buildWDK.groovy
  vars/buildWDKAutoSwitch.groovy
  vars/gradleWrapper.groovy
  vars/javaLibCheck.groovy
  vars/publish.groovy
  vars/utils.groovy
Labels: add, atlas-stream, improve

#44 Fix test labels config
  src/net/wooga/jenkins/pipeline/config/Platform.groovy
  test/groovy/net/wooga/jenkins/pipeline/config/PlatformSpec.groovy
Labels: atlas-stream, fix
